"""Guide-reviewed accessory descriptions layered on the safe v0.28 wording."""

from ui_safe_v28_overrides import OVERRIDES as V28_OVERRIDES


OVERRIDES = dict(V28_OVERRIDES)
OVERRIDES.update(
    {
        ("equipment_description", 0): "불 공격에 강함",
    ("equipment_description", 1): "물 공격에 강함",
        ("equipment_description", 2): "헤모지 상태 방지",
        ("equipment_description", 3): "체력 회복량 증가",
        ("equipment_description", 4): "전투 경험치 2배",
        ("equipment_description", 5): "마력 10% 상승",
        ("equipment_description", 6): "수면 상태 방지",
        ("equipment_description", 7): "촌가라 방어력 30% 상승",
        ("equipment_description", 8): "던지기 +1",
        ("equipment_description", 9): "공격력 50% 상승",
        ("equipment_description", 10): "실명 방지",
        ("equipment_description", 11): "명중 크게 상승",
        ("equipment_description", 12): "던지기 강화",
        ("equipment_description", 13): "일부 적에게 강함",
        ("equipment_description", 14): "공격이 반드시 명중",
        ("equipment_description", 15): "성장 시 최대 체력 증가량 상승",
        ("equipment_description", 16): "마법사 마력 30% 상승",
        ("equipment_description", 17): "명중 상승",
        ("equipment_description", 18): "민첩 10% 상승",
        ("equipment_description", 19): "민첩 30% 상승",
        ("equipment_description", 20): "점프 +1",
        ("equipment_description", 21): "반격 상승",
        ("equipment_description", 22): "받기 +1",
        ("equipment_description", 23): "받기가 되던지기로 변화",
        ("equipment_description", 24): "소비 마력 절반",
        ("equipment_description", 25): "공격력 30% 상승",
        ("equipment_description", 26): "이가 반격 피해 증가",
        ("equipment_description", 27): "작용 불명",
        ("equipment_description", 28): "쿠쿠루 행동 시 주변 아군 회복",
        ("equipment_description", 29): "물건 입수율 상승",
        ("equipment_description", 30): "좋은 물건 입수",
        ("equipment_description", 31): "작용 불명",
        ("equipment_description", 32): "돌 상태 방지",
        ("equipment_description", 33): "아크 전용 작용 불명",
        ("equipment_description", 34): "마력 50% 상승",
        ("equipment_description", 35): "마력 30% 상승",
        ("equipment_description", 36): "방향잡이 피리가 전체에 적용",
        ("equipment_description", 37): "해로운 기운 방지",
        ("equipment_description", 38): "방어력 50% 상승",
        ("equipment_description", 39): "방어력 30% 상승",
        ("equipment_description", 40): "방어율 상승",
        ("equipment_description", 41): "마법사 공격력 70% 상승",
        ("equipment_description", 42): "심안법 범위 확대",
        ("equipment_description", 43): "마물 경험치가 촌가라에게",
        ("equipment_description", 44): "마법 봉인 상태 방지",
        ("equipment_description", 45): "회피율 상승",
        ("equipment_description", 46): "공격력 10% 상승",
        ("equipment_description", 47): "공격 피해 편차 증가",
        ("equipment_description", 48): "쿠쿠루 부활 시 최대 체력 회복",
        ("equipment_description", 49): "피해 편차 증가",
        ("equipment_description", 50): "방어력 10% 상승",
        ("equipment_description", 51): "작용 불명",
        ("equipment_description", 52): "작용 불명",
        ("equipment_description", 53): "작용 불명",
        ("equipment_description", 54): "작용 불명",
        ("equipment_description", 55): "매 행동 체력 회복",
        ("equipment_description", 56): "토슈 명중 크게 상승",
        ("equipment_description", 57): "모든 이상 상태 방지",
        ("equipment_description", 58): "포코 마력 30% 상승",
        ("equipment_description", 59): "마비 상태 방지",
        ("equipment_description", 60): "토슈 비기에 마비 부여",
        ("equipment_description", 61): "일부 적에게 강함",
        ("equipment_description", 62): "아크 매 행동 마력 회복",
        ("equipment_description", 63): "?????",
    }
)

# Keep one-line help text within the verified 14-cell width. These are wording
# changes only; the guide-reviewed meanings from v0.28 remain unchanged.
OVERRIDES.update(
    {
        ("skill_description", 1): "불바다로 범위 적에게 피해",
        ("skill_description", 3): "이공간 공격으로 적 피해",
        ("skill_description", 5): "별을 내려 주변 적 공격",
        ("skill_description", 14): "적 하나를 마비로 변화",
        ("skill_description", 17): "범위 아군 공격력 상승",
        ("skill_description", 24): "아군 방향을 포코처럼 변화",
        ("skill_description", 25): "큰 불꽃으로 범위 적 피해",
        ("skill_description", 27): "눈보라로 범위 적에게 피해",
        ("skill_description", 28): "돌풍으로 범위 적에게 피해",
        ("skill_description", 30): "전기로 범위 적에게 피해",
        ("skill_description", 38): "회복 마물로 체력 회복",
        ("skill_description", 48): "라이진 합체 마법",
        ("skill_description", 49): "후우진 합체 마법",
    }
)
