"""Safe wording overrides that require no new COMM.IMG glyph planes."""

OVERRIDES = {
    # Equipment/accessory names.
    ("equipment_name", 0): "불꽃 방어",
    ("equipment_name", 1): "차가운 바람 방어",
    ("equipment_name", 2): "헤모지 방지",
    ("equipment_name", 4): "비단 허리 장식",
    ("equipment_name", 7): "강화 팔",
    ("equipment_name", 9): "신기한 장갑",
    ("equipment_name", 12): "던지기 두루마리",
    ("equipment_name", 14): "보라 레이저",
    ("equipment_name", 16): "기도 구슬",
    ("equipment_name", 17): "장로 허리 장식",
    ("equipment_name", 19): "하이퍼 신발",
    ("equipment_name", 23): "마력 팔찌",
    ("equipment_name", 27): "마수의 이빨",
    ("equipment_name", 28): "바다 바람의 노래",
    ("equipment_name", 29): "조가비",
    ("equipment_name", 30): "일각수 장식",
    ("equipment_name", 31): "비애의 안경",
    ("equipment_name", 34): "신기한 반지",
    ("equipment_name", 37): "몸 이상 방지 반지",
    ("equipment_name", 38): "신기한 막이",
    ("equipment_name", 39): "전사 방어",
    ("equipment_name", 40): "장로 막이",
    ("equipment_name", 41): "강한 마법봉",
    ("equipment_name", 45): "모조상",
    ("equipment_name", 47): "신기한 검",
    ("equipment_name", 49): "요동치는 돌",
    ("equipment_name", 50): "갑옷 돌",
    ("equipment_name", 51): "연인의 돌 1",
    ("equipment_name", 52): "연인의 돌 2",
    ("equipment_name", 53): "연인의 돌 3",
    ("equipment_name", 54): "연인의 돌 4",
    ("equipment_name", 56): "꽃 도감",
    ("equipment_name", 57): "크라우스 도감",
    ("equipment_name", 62): "용자의 증거",

    # Equipment/accessory descriptions.
    ("equipment_description", 0): "불 공격 피해 감소",
    ("equipment_description", 1): "차가운 바람 피해 감소",
    ("equipment_description", 3): "회복량 증가",
    ("equipment_description", 4): "경험치 2배",
    ("equipment_description", 5): "마력 상승",
    ("equipment_description", 7): "촌가라 방어력 상승",
    ("equipment_description", 8): "던지기 단계 1",
    ("equipment_description", 9): "공격력 크게 상승",
    ("equipment_description", 10): "어두운 기운 방지",
    ("equipment_description", 11): "명중 상승",
    ("equipment_description", 12): "던지기가 강하게 변화",
    ("equipment_description", 13): "일부 적에 강함",
    ("equipment_description", 15): "성장 시 최대 체력 증가",
    ("equipment_description", 16): "마법사 마력 상승",
    ("equipment_description", 17): "명중 상승",
    ("equipment_description", 18): "민첩 조금 상승",
    ("equipment_description", 19): "민첩 크게 상승",
    ("equipment_description", 20): "점프 단계 1",
    ("equipment_description", 21): "반격 상승",
    ("equipment_description", 22): "받기 단계 1",
    ("equipment_description", 24): "소비 마력 절반",
    ("equipment_description", 25): "공격력 상승",
    ("equipment_description", 27): "작용 불명",
    ("equipment_description", 29): "물건 입수 상승",
    ("equipment_description", 30): "좋은 물건 입수",
    ("equipment_description", 31): "작용 불명",
    ("equipment_description", 32): "몸 마비 방지",
    ("equipment_description", 33): "아크 전용 작용 불명",
    ("equipment_description", 34): "마력 크게 상승",
    ("equipment_description", 35): "마력 상승",
    ("equipment_description", 36): "포코의 방향 바꾸기가 전체에 적용",
    ("equipment_description", 37): "해로운 기운 방지",
    ("equipment_description", 38): "방어력 크게 상승",
    ("equipment_description", 39): "방어력 상승",
    ("equipment_description", 41): "마법사 공격력 크게 상승",
    ("equipment_description", 43): "촌가라 마물이 경험치 받음",
    ("equipment_description", 44): "마법 봉인 방지",
    ("equipment_description", 46): "공격력 조금 상승",
    ("equipment_description", 50): "방어력 조금 상승",
    ("equipment_description", 51): "작용 불명",
    ("equipment_description", 52): "작용 불명",
    ("equipment_description", 53): "작용 불명",
    ("equipment_description", 54): "작용 불명",
    ("equipment_description", 56): "토슈 공격 명중 상승",
    ("equipment_description", 58): "포코 마력 상승",
    ("equipment_description", 60): "토슈 비기에 마비 부여",
    ("equipment_description", 61): "일부 적에 강함",
    ("equipment_description", 62): "아크 매 행동 마력 회복",

    # Consumables.
    ("consumable_name", 0): "거미줄",
    ("consumable_name", 1): "기운 음식",
    ("consumable_name", 8): "위험한 풀",
    ("consumable_name", 11): "작은 폭발 구슬",
    ("consumable_name", 12): "큰 폭발 구슬",
    ("consumable_name", 13): "만병약",
    ("consumable_name", 22): "마력의 풀",
    ("consumable_name", 23): "마력의 물",
    ("consumable_name", 25): "쓴 풀",
    ("consumable_name", 26): "몸 마비 회복침",
    ("consumable_name", 27): "마법 봉인 회복침",
    ("consumable_name", 28): "마물 항아리",
    ("consumable_description", 2): "단계 1 상승",
    ("consumable_description", 8): "해로운 기운 부여",
    ("consumable_description", 14): "해로운 기운 회복",
    ("consumable_description", 24): "명중 감소",
    ("consumable_description", 26): "몸 마비 회복",
    ("consumable_description", 27): "마법 봉인 회복",
    ("consumable_description", 28): "촌가라의 마물 부르기",

    # Player skills. Names and effects follow the Korean walkthrough tables
    # on printed pages 92-95, with the executable retained as effect authority.
    ("skill_name", 1): "번 그라운드",
    ("skill_name", 2): "전체 회복",
    ("skill_name", 3): "게일 플래시",
    ("skill_name", 4): "슬로우 에너미",
    ("skill_name", 5): "별 내리기",
    ("skill_name", 6): "회복",
    ("skill_name", 7): "해로운 기운 제거",
    ("skill_name", 8): "사일런트",
    ("skill_name", 9): "리프레시",
    ("skill_name", 10): "하늘의 심판",
    ("skill_name", 11): "부활",
    ("skill_name", 12): "디바이드",
    ("skill_name", 13): "토슈 비기",
    ("skill_name", 14): "봉인검",
    ("skill_name", 15): "진공검",
    ("skill_name", 16): "그림자검",
    ("skill_name", 17): "전투 큰 북",
    ("skill_name", 18): "황사자태고",
    ("skill_name", 19): "기합 나팔",
    ("skill_name", 20): "비틀비틀 나팔",
    ("skill_name", 21): "치유의 하프",
    ("skill_name", 22): "느림의 연주",
    ("skill_name", 23): "위타천 오카리나",
    ("skill_name", 24): "방향잡이 피리",
    ("skill_name", 25): "대폭발",
    ("skill_name", 26): "드림 노크",
    ("skill_name", 27): "다이아몬드 더스트",
    ("skill_name", 28): "바람 검",
    ("skill_name", 29): "불의 장막",
    ("skill_name", 30): "전기 폭풍",
    ("skill_name", 31): "공간 이동",
    ("skill_name", 32): "심안법",
    ("skill_name", 33): "악령 광선",
    ("skill_name", 34): "회오리 차기",
    ("skill_name", 35): "유성폭",
    ("skill_name", 36): "유령 파동",
    ("skill_name", 37): "멸장열파",
    ("skill_name", 38): "회복 마물",
    ("skill_name", 39): "모프리",
    ("skill_name", 40): "후우진",
    ("skill_name", 41): "라이진",
    ("skill_name", 42): "헤모지",
    ("skill_name", 43): "강화 마물",
    ("skill_name", 44): "조사",
    ("skill_name", 45): "초코",
    ("skill_name", 48): "바람 전기",
    ("skill_name", 49): "바람 전기",
    ("skill_name", 50): "몸 가져오기",
    ("skill_name", 51): "폭발 수리검",
    ("skill_name", 55): "불과 전기",
    ("skill_name", 56): "먼지 마법진",
    ("skill_name", 57): "요미의 바람",
    ("skill_name", 58): "기운 없음",
    ("skill_description", 1): "불바다로 일정 범위 적에게 피해",
    ("skill_description", 2): "이상 상태와 체력 회복",
    ("skill_description", 3): "다른 공간 공격으로 적에게 피해",
    ("skill_description", 4): "일정 범위 적 민첩 감소",
    ("skill_description", 5): "별을 내려 주변 적에게 피해",
    ("skill_description", 6): "일정 범위 아군 체력 회복",
    ("skill_description", 7): "해로운 기운 제거",
    ("skill_description", 8): "적의 마법 봉인",
    ("skill_description", 9): "아군의 이상 상태 회복",
    ("skill_description", 10): "천사의 광선 공격",
    ("skill_description", 11): "쓰러진 아군 부활",
    ("skill_description", 12): "적 체력을 줄여 아군 회복",
    ("skill_description", 13): "적 하나에 강한 검격",
    ("skill_description", 14): "적 하나를 마비 상태로 변화",
    ("skill_description", 15): "전방의 적 공격",
    ("skill_description", 16): "달려가며 적 공격",
    ("skill_description", 17): "일정 범위 아군 공격력 상승",
    ("skill_description", 18): "파동 광선으로 적 공격",
    ("skill_description", 19): "먼 적을 소리로 공격",
    ("skill_description", 20): "다수의 폭발 구슬 발사",
    ("skill_description", 21): "일정 범위 아군 체력 회복",
    ("skill_description", 22): "일정 범위 적 민첩 감소",
    ("skill_description", 23): "일정 범위 아군 민첩 상승",
    ("skill_description", 24): "아군을 포코와 같은 방향으로 변화",
    ("skill_description", 25): "큰 불꽃으로 일정 범위 적에게 피해",
    ("skill_description", 26): "일정 범위 적을 잠들게 함",
    ("skill_description", 27): "눈보라로 일정 범위 적에게 피해",
    ("skill_description", 28): "돌풍으로 일정 범위 적에게 피해",
    ("skill_description", 29): "불꽃 장막 생성",
    ("skill_description", 30): "전기로 일정 범위 적에게 피해",
    ("skill_description", 31): "주변 아군과 공간 이동",
    ("skill_description", 32): "적 하나 고정",
    ("skill_description", 33): "고정한 적에게 광선 발사",
    ("skill_description", 34): "주변 적을 회전하며 공격",
    ("skill_description", 35): "회오리로 올려 내리침",
    ("skill_description", 36): "분신을 날려 공격",
    ("skill_description", 37): "자신보다 약한 적을 소멸",
    ("skill_description", 38): "회복 마물을 불러 체력 회복",
    ("skill_description", 39): "모프리를 불러 길 생성",
    ("skill_description", 40): "후우진을 부름",
    ("skill_description", 41): "라이진을 부름",
    ("skill_description", 42): "헤모지를 불러 적을 변화",
    ("skill_description", 43): "강화 마물을 불러 힘 상승",
    ("skill_description", 44): "마물의 힘 조사",
    ("skill_description", 45): "초코를 부름",
    ("skill_description", 46): "아군 체력 회복",
    ("skill_description", 47): "갈 수 없는 곳에 길 생성",
    ("skill_description", 48): "라이진과 함께하는 강한 마법",
    ("skill_description", 49): "후우진과 함께하는 강한 마법",
    ("skill_description", 50): "적의 몸으로 이동",
    ("skill_description", 51): "주변에 수리검 난사",
    ("skill_description", 52): "자폭 공격",
    ("skill_description", 53): "큰 무기를 던져 공격",
    ("skill_description", 54): "주변 적에게 피해",
    ("skill_description", 55): "주변 적에게 피해",
    ("skill_description", 56): "직선상의 적 공격",
    ("skill_description", 57): "바람으로 적에게 피해",
    ("skill_description", 58): "적을 헤모지 상태로 변화",

    # Semantic monster-name alternatives. Canonical proper names remain preserved.
    ("character_name", 11): "죽은 병사",
    ("character_name", 22): "정령",
    ("character_name", 24): "유령",
    ("character_name", 26): "거대 파리",
    ("character_name", 28): "빨간 죽은 병사",
    ("character_name", 29): "검은 죽은 병사",
    ("character_name", 38): "사령 마법사",
    ("character_name", 40): "어두운 법사",
    ("character_name", 43): "연무 괴물",
    ("character_name", 48): "검사",
    ("character_name", 51): "해로운 연기",
    ("character_name", 53): "왕잠자리",
    ("character_name", 54): "식인 식물",
    ("character_name", 56): "정령 지배자",
    ("character_name", 62): "바위 거인",
    ("character_name", 66): "불의 거인",
    ("character_name", 67): "구리 용",
    ("character_name", 68): "거대 뱀",
    ("character_name", 74): "불 도깨비",

    # Generic location wording where the proper noun is not changed.
    ("location_name", 7): "왕의 방",
    ("location_name", 15): "팔렌시아 지하 보관소",
    ("location_name", 18): "이계",
    ("location_name", 35): "지하 승강기",
    ("location_name", 40): "토우빌 바위산",
    ("location_name", 54): "탑 꼭대기",
}
